### PR TITLE
add macOS support

### PR DESCRIPTION
**Pull request by oluan**
Hi, this patch adds support for macOS and Homebrew package manager.
Additionally, this patch fixes two small bugs.

image
image

### CODE REVIEW

**Comment by 13-CF** [comment]
Looks good, I'm almost finished setting up a 'hackintosh', so once that's done I'll do some testing then merge your PR when all is good. 

Do you think it'd be better if we made the program display an error message if the user doesn't have Homebrew installed?

**Comment by oluan** [comment]
> Looks good, I'm almost finished setting up a 'hackintosh', so once that's done I'll do some testing then merge your PR.
> 
> Do you think it'd be better if we made the program display an error message if the user doesn't have Homebrew installed?

Let me know what do you think of this warning approach.

**Review by 0x1mastermind — APPROVED** [review]
Very good, the performace isn't affected and is very useful. Thanks to contribute. 😊

**Comment by 13-CF** [comment]
Thanks for all the work you put in! I'll add some credit in the README next time I'm on my machine (currently using that app).

Got my mac up and running so development should be a little easier for mac.

**Pull request merged**
